flat_ai_reporting.Rmd:
  path: dev/flat_ai_reporting.Rmd
  state: active
  R:
  - R/clean_llm_response.R
  - R/extract_structure.R
  - R/generate_description.R
  - R/generate_plot_story.R
  - R/generate_report_summary.R
  - R/generate_section_summary.R
  - R/profile_data.R
  - R/slugify.R
  tests:
  - tests/testthat/test-clean_llm_response.R
  - tests/testthat/test-generate_plot_story.R
  - tests/testthat/test-slugify.R
  - tests/testthat/test-generate_section_summary.R
  - tests/testthat/test-generate_report_summary.R
  vignettes: vignettes/ai-analysis-architecture.Rmd
  inflate:
    flat_file: dev/flat_ai_reporting.Rmd
    vignette_name: AI Analysis Architecture
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
    clean: ask
    codecov: false
flat_reports.Rmd:
  path: dev/flat_reports.Rmd
  state: active
  R: R/generate_report.R
  tests: tests/testthat/test-regional-report.R
  vignettes: vignettes/get-started.Rmd
  inflate:
    flat_file: dev/flat_reports.Rmd
    vignette_name: Get Started
    open_vignette: true
    check: false
    document: true
    overwrite: 'yes'
    clean: ask
    codecov: false
