flat_ai_reporting.Rmd:
  path: dev/flat_ai_reporting.Rmd
  state: active
  R:
  - R/clean_llm_response.R
  - R/extract_structure.R
  - R/generate_description.R
  - R/generate_plot_story.R
  - R/generate_report_summary.R
  - R/generate_section_summary.R
  - R/profile_data.R
  - R/slugify.R
  tests:
  - tests/testthat/test-clean_llm_response.R
  - tests/testthat/test-generate_plot_story.R
  - tests/testthat/test-slugify.R
  - tests/testthat/test-generate_section_summary.R
  - tests/testthat/test-generate_report_summary.R
  vignettes: vignettes/ai-powered-reports.Rmd
  inflate:
    flat_file: dev/flat_ai_reporting.Rmd
    vignette_name: AI Powered Reports
    open_vignette: true
    check: false
    document: true
    overwrite: 'yes'
    clean: ask
    codecov: false
flat_plots_country.Rmd:
  path: dev/flat_plots_country.Rmd
  state: active
  R:
  - R/plot_ctr_asylum.R
  - R/plot_ctr_destination.R
  - R/plot_ctr_diff_in_pop_groups.R
  - R/plot_ctr_disp_migrant.R
  - R/plot_ctr_keyfig.R
  - R/plot_ctr_location.R
  - R/plot_ctr_origin_history.R
  - R/plot_ctr_origin_recognition.R
  - R/plot_ctr_population_type_abs.R
  - R/plot_ctr_population_type_per_year.R
  - R/plot_ctr_population_type_perc.R
  - R/plot_ctr_process.R
  - R/plot_ctr_processing_time.R
  - R/plot_ctr_pyramid.R
  - R/plot_ctr_recognition.R
  - R/plot_ctr_solution.R
  - R/plot_ctr_solution_recognition.R
  - R/plot_ctr_treemap.R
  tests:
  - tests/testthat/test-plot_ctr_keyfig.R
  - tests/testthat/test-plot_ctr_population_type_per_year.R
  - tests/testthat/test-plot_ctr_origin_history.R
  - tests/testthat/test-plot_ctr_origin_recognition.R
  - tests/testthat/test-plot_ctr_location.R
  - tests/testthat/test-plot_ctr_recognition.R
  - tests/testthat/test-plot_ctr_asylum.R
  - tests/testthat/test-plot_ctr_process.R
  - tests/testthat/test-plot_ctr_processing_time.R
  - tests/testthat/test-plot_ctr_solution.R
  - tests/testthat/test-plot_ctr_solution_recognition.R
  - tests/testthat/test-plot_ctr_disp_migrant.R
  vignettes: vignettes/country-report-visualizations.Rmd
  inflate:
    flat_file: dev/flat_plots_country.Rmd
    vignette_name: Country Report Visualizations
    open_vignette: true
    check: false
    document: true
    overwrite: 'yes'
    clean: ask
    codecov: false
flat_plots_region.Rmd:
  path: dev/flat_plots_region.Rmd
  state: active
  R:
  - R/plot_reg_decrease.R
  - R/plot_reg_increase.R
  - R/plot_reg_map.R
  - R/plot_reg_origin_dest.R
  - R/plot_reg_population_type_abs.R
  - R/plot_reg_population_type_per_year.R
  - R/plot_reg_prop_origin.R
  - R/plot_reg_rsd.R
  - R/plot_reg_share.R
  - R/plot_reg_solution.R
  - R/plot_reg_treemap.R
  tests:
  - tests/testthat/test-plot_reg_treemap.R
  - tests/testthat/test-plot_reg_share.R
  - tests/testthat/test-plot_reg_population_type_per_year.R
  - tests/testthat/test-plot_reg_origin_dest.R
  - tests/testthat/test-plot_reg_decrease.R
  - tests/testthat/test-plot_reg_increase.R
  - tests/testthat/test-plot_reg_prop_origin.R
  - tests/testthat/test-plot_reg_rsd.R
  - tests/testthat/test-plot_reg_solution.R
  - tests/testthat/test-plot_reg_map.R
  vignettes: vignettes/regional-report-visualizations.Rmd
  inflate:
    flat_file: dev/flat_plots_region.Rmd
    vignette_name: Regional Report Visualizations
    open_vignette: false
    check: false
    document: true
    overwrite: 'yes'
    clean: ask
    codecov: false
flat_reports.Rmd:
  path: dev/flat_reports.Rmd
  state: active
  R: R/generate_report.R
  tests: tests/testthat/test-regional-report.R
  vignettes: vignettes/generate-reports.Rmd
  inflate:
    flat_file: dev/flat_reports.Rmd
    vignette_name: Generate Reports
    open_vignette: false
    check: false
    document: true
    overwrite: 'yes'
    clean: ask
    codecov: false
